apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: db
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: keycloak
  selector:
    app: keycloak