// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: upload-server.proto

package upload_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PresighedURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId              string   `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UserId              string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AllowedFormats      []string `protobuf:"bytes,3,rep,name=allowedFormats,proto3" json:"allowedFormats,omitempty"`
	MaxSize             uint64   `protobuf:"varint,4,opt,name=maxSize,proto3" json:"maxSize,omitempty"`
	IsoTimeOfExpiration string   `protobuf:"bytes,5,opt,name=isoTimeOfExpiration,proto3" json:"isoTimeOfExpiration,omitempty"`
	CallbackAdrr        string   `protobuf:"bytes,6,opt,name=callbackAdrr,proto3" json:"callbackAdrr,omitempty"`
}

func (x *PresighedURLRequest) Reset() {
	*x = PresighedURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_upload_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresighedURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresighedURLRequest) ProtoMessage() {}

func (x *PresighedURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upload_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresighedURLRequest.ProtoReflect.Descriptor instead.
func (*PresighedURLRequest) Descriptor() ([]byte, []int) {
	return file_upload_server_proto_rawDescGZIP(), []int{0}
}

func (x *PresighedURLRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *PresighedURLRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PresighedURLRequest) GetAllowedFormats() []string {
	if x != nil {
		return x.AllowedFormats
	}
	return nil
}

func (x *PresighedURLRequest) GetMaxSize() uint64 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *PresighedURLRequest) GetIsoTimeOfExpiration() string {
	if x != nil {
		return x.IsoTimeOfExpiration
	}
	return ""
}

func (x *PresighedURLRequest) GetCallbackAdrr() string {
	if x != nil {
		return x.CallbackAdrr
	}
	return ""
}

type PresighedURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *PresighedURLResponse) Reset() {
	*x = PresighedURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_upload_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresighedURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresighedURLResponse) ProtoMessage() {}

func (x *PresighedURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upload_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresighedURLResponse.ProtoReflect.Descriptor instead.
func (*PresighedURLResponse) Descriptor() ([]byte, []int) {
	return file_upload_server_proto_rawDescGZIP(), []int{1}
}

func (x *PresighedURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_upload_server_proto protoreflect.FileDescriptor

var file_upload_server_proto_rawDesc = []byte{
	0x0a, 0x13, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x22, 0xdf, 0x01, 0x0a, 0x13, 0x50, 0x72, 0x65, 0x73, 0x69, 0x67, 0x68,
	0x65, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66,
	0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26,
	0x0a, 0x0e, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x46,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x30, 0x0a, 0x13, 0x69, 0x73, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x66, 0x45, 0x78, 0x70,
	0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x69,
	0x73, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x66, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x41, 0x64,
	0x72, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x41, 0x64, 0x72, 0x72, 0x22, 0x28, 0x0a, 0x14, 0x50, 0x72, 0x65, 0x73, 0x69, 0x67,
	0x68, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x32, 0x6f, 0x0a, 0x0c, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x12, 0x5f, 0x0a, 0x14, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x72, 0x65, 0x73,
	0x69, 0x67, 0x6e, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x12, 0x22, 0x2e, 0x75, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x69, 0x67, 0x68,
	0x65, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x75,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x65,
	0x73, 0x69, 0x67, 0x68, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x19, 0x5a, 0x17, 0x2e, 0x2e, 0x2f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2f, 0x75,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_upload_server_proto_rawDescOnce sync.Once
	file_upload_server_proto_rawDescData = file_upload_server_proto_rawDesc
)

func file_upload_server_proto_rawDescGZIP() []byte {
	file_upload_server_proto_rawDescOnce.Do(func() {
		file_upload_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_upload_server_proto_rawDescData)
	})
	return file_upload_server_proto_rawDescData
}

var file_upload_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_upload_server_proto_goTypes = []interface{}{
	(*PresighedURLRequest)(nil),  // 0: upload_server.PresighedURLRequest
	(*PresighedURLResponse)(nil), // 1: upload_server.PresighedURLResponse
}
var file_upload_server_proto_depIdxs = []int32{
	0, // 0: upload_server.UploadServer.GeneratePresignedURL:input_type -> upload_server.PresighedURLRequest
	1, // 1: upload_server.UploadServer.GeneratePresignedURL:output_type -> upload_server.PresighedURLResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_upload_server_proto_init() }
func file_upload_server_proto_init() {
	if File_upload_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_upload_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresighedURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_upload_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresighedURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_upload_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_upload_server_proto_goTypes,
		DependencyIndexes: file_upload_server_proto_depIdxs,
		MessageInfos:      file_upload_server_proto_msgTypes,
	}.Build()
	File_upload_server_proto = out.File
	file_upload_server_proto_rawDesc = nil
	file_upload_server_proto_goTypes = nil
	file_upload_server_proto_depIdxs = nil
}
