apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: console
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: s3
  selector:
    app: minio