apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-vol
  labels:
    app: minio
spec:
  claimRef:
    name: minio-pvc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/volume3