apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-ui-vol
  labels:
    app: db-ui
spec:
  claimRef:
    name: db-ui-pvc
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/volume2