apiVersion: v1
kind: Service
metadata:
  name: db-ui
  labels:
    app: db-ui
spec:
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 80
    protocol: TCP
    name: db-ui
  selector:
    app: db-ui