apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-vol
  labels:
    app: db
spec:
  claimRef:
    name: db-pvc
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/volume1